package view;

import java.awt.Point;
import controladores.ControleCasas;
import fabrica.FabricaCasaTabuleiro;

public class PovoarCasasTabuleiro {

		public PovoarCasasTabuleiro() {
			FabricaCasaTabuleiro fabricaCasas = new FabricaCasaTabuleiro();
			
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(1, "N", new Point(41, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(2, "N", new Point(88, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(3, "S", new Point(139, 475), 52));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(4, "N", new Point(186, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(5, "E", new Point(235, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(6, "N", new Point(279, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(7, "N", new Point(327, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(8, "E", new Point(379, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(9, "N", new Point(426, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(10, "N", new Point(472, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(11, "N", new Point(521, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(12, "S", new Point(568, 475), 59));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(13, "N", new Point(615, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(14, "S", new Point(665, 475), 20));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(15, "N", new Point(713, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(16, "N", new Point(760, 475)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(17, "N", new Point(760, 430)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(18, "N", new Point(760, 390)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(19, "N", new Point(760, 342)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(20, "N", new Point(760, 297)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(21, "N", new Point(760, 255)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(22, "N", new Point(760, 207)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(23, "S", new Point(760, 164), 29));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(24, "N", new Point(760, 116)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(25, "N", new Point(760, 72)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(26, "N", new Point(760, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(27, "N", new Point(710, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(28, "N", new Point(665, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(29, "N", new Point(615, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(30, "N", new Point(568, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(31, "N", new Point(520, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(32, "N", new Point(472, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(33, "E", new Point(425, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(34, "E", new Point(377, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(35, "N", new Point(327, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(36, "N", new Point(280, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(37, "N", new Point(231, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(38, "N", new Point(183, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(39, "N", new Point(137, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(40, "N", new Point(89, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(41, "N", new Point(42, 24)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(42, "N", new Point(42, 70)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(43, "N", new Point(42, 115)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(44, "N", new Point(42, 160)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(45, "N", new Point(42, 203)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(46, "N", new Point(42, 251)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(47, "S", new Point(42, 294), 80));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(48, "N", new Point(42, 342)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(49, "N", new Point(42, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(50, "N", new Point(89, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(51, "E", new Point(137, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(52, "N", new Point(183, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(53, "N", new Point(232, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(54, "N", new Point(278, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(55, "M", new Point(328, 386), 7));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(56, "S", new Point(375, 386), 89));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(57, "N", new Point(424, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(58, "N", new Point(473, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(59, "N", new Point(520, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(60, "E", new Point(566, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(61, "N", new Point(615, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(62, "N", new Point(662, 386)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(63, "N", new Point(662, 342)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(64, "N", new Point(662, 295)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(65, "N", new Point(662, 251)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(66, "N", new Point(662, 207)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(67, "M", new Point(662, 162), 21));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(68, "N", new Point(662, 115)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(69, "N", new Point(615, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(70, "N", new Point(569, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(71, "N", new Point(520, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(72, "N", new Point(473, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(73, "N", new Point(425, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(74, "N", new Point(377, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(75, "M", new Point(326, 113), 36));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(76, "N", new Point(279, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(77, "N", new Point(231, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(78, "N", new Point(184, 113)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(79, "M", new Point(136, 113), 43));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(80, "N", new Point(136, 162)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(81, "N", new Point(136, 207)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(82, "N", new Point(136, 251)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(83, "M", new Point(136, 293), 50));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(84, "N", new Point(183, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(85, "N", new Point(231, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(86, "N", new Point(281, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(87, "E", new Point(328, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(88, "N", new Point(378, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(89, "N", new Point(424, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(90, "N", new Point(470, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(91, "N", new Point(523, 293)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(92, "M", new Point(566, 293), 64));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(93, "N", new Point(566, 252)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(94, "N", new Point(566, 205)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(95, "N", new Point(519, 205)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(96, "N", new Point(472, 205)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(97, "M", new Point(425, 205), 72));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(98, "N", new Point(377, 205)));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(99, "M", new Point(329, 205), 86));
			ControleCasas.getInstance().addCasa(fabricaCasas.criar(100, "F", new Point(280, 209)));		
		}
		
}
